### ISSUE TITLE
Comparing unrelated types in RDFStatistics 

### ISSUE THREAD

**Issue by LorenzBuehmann** [SANSA-Stack/SANSA-RDF#58]
https://github.com/SANSA-Stack/SANSA-RDF/blob/4b1e3ab8c7f6f275b22814b366f355b0a708bb24/sansa-rdf-spark/src/main/scala/net/sansa_stack/rdf/spark/stats/RDFStatistics.scala#L129

The line is just an example and the issue occurs in multiple places in the code:
```scala
`triple.getPredicate.toString().equals(RDFS.subClassOf)`
```
`RDFS.subClassOf` is of type `org.apache.jena.rdf.model.Resource`, thus, `equals` will always return `false`. That means many stats will be wrong.

**Comment by GezimSejdiu** [comment]
Many thanks, Lorenz for pointing it out. 
Indeed, this is wrong. When I did a bit of refactoring recently I also change the prefixes from just [string defined](https://github.com/SANSA-Stack/SANSA-RDF/blob/develop/sansa-rdf-spark/src/main/scala/net/sansa_stack/rdf/spark/utils/Prefixes.scala) to a Jena vocabulary where this issue appear. This mean that the evaluation of Stats has been performed on string matching instead of `Resource`. Now it matches` Node` with another  `Node`.

Best,
